# Generated by Django 4.2.7 on 2023-11-29 09:19

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=765)),
                ('featured_image', models.ImageField(upload_to='blogs/image')),
                ('author', models.CharField(max_length=255)),
                ('content', django_quill.fields.QuillField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
