# Generated by Django 4.2.7 on 2023-11-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_atHome',
            field=models.BooleanField(default=False),
        ),
    ]
